apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: porfavorfunciona
  annotations:
    spec.ingressClassName: "nginx"
spec:
  rules:
    - host: k8s.devops.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mongo-express
              port: 
                number: 8081
